// This file is auto-generated by TanStack Router.
// It will be replaced when you run `vite dev` or `vite build`.
// Do not edit this file manually.

import { Route as rootRoute } from './routes/__root'
import { Route as indexRoute } from './routes/index'
import { Route as blogSlugRoute } from './routes/blog.$slug'
import { Route as docsRoute } from './routes/docs.$'
import { Route as sitemapRoute } from './routes/sitemap.xml'

const routeTree = rootRoute.addChildren([
  indexRoute,
  blogSlugRoute,
  docsRoute,
  sitemapRoute,
])

export { routeTree }
