/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: src/lib/queries.ts
// Variable: ARTICLES_QUERY
// Query: *[_type == "article"] | order(title asc) { _id, title }
export type ARTICLES_QUERY_RESULT = Array<{
  _id: string
  title: string | null
}>

// Source: src/lib/queries.ts
// Variable: BLOG_POSTS_QUERY
// Query: *[_type == "blogPost"] | order(title asc) { _id, title }
export type BLOG_POSTS_QUERY_RESULT = Array<{
  _id: string
  title: string | null
}>

// Source: src/lib/queries.ts
// Variable: BLOG_POST_BY_SLUG_QUERY
// Query: *[_type == "blogPost" && slug.current == $slug][0]{ _id, title, body }
export type BLOG_POST_BY_SLUG_QUERY_RESULT = {
  _id: string
  title: string | null
  body: Array<{
    _key: string
    _type: string
    [key: string]: unknown
  }> | null
} | null

// Source: src/lib/queries.ts
// Variable: ARTICLE_BY_SLUG_QUERY
// Query: *[_type == "article" && slug.current == $slug][0]{ _id, title, body }
export type ARTICLE_BY_SLUG_QUERY_RESULT = {
  _id: string
  title: string | null
  body: Array<{
    _key: string
    _type: string
    [key: string]: unknown
  }> | null
} | null

// Query TypeMap
import '@sanity/client'
declare module '@sanity/client' {
  interface SanityQueries {
    '*[_type == "article"] | order(title asc) { _id, title }': ARTICLES_QUERY_RESULT
    '*[_type == "blogPost"] | order(title asc) { _id, title }': BLOG_POSTS_QUERY_RESULT
    '*[_type == "blogPost" && slug.current == $slug][0]{ _id, title, body }': BLOG_POST_BY_SLUG_QUERY_RESULT
    '*[_type == "article" && slug.current == $slug][0]{ _id, title, body }': ARTICLE_BY_SLUG_QUERY_RESULT
  }
}
