/**
 * Generated by Sanity TypeGen — placeholder for SPA example.
 * Run `pnpm typegen` to regenerate from studio schema.
 */

// Source: src/lib/queries.ts
export type ARTICLES_QUERY_RESULT = Array<{
  _id: string
  title: string | null
}>

export type BLOG_POSTS_QUERY_RESULT = Array<{
  _id: string
  title: string | null
}>

export type BLOG_POST_BY_SLUG_QUERY_RESULT = {
  _id: string
  title: string | null
  body: Array<{
    _key: string
    _type: string
    [key: string]: unknown
  }> | null
} | null

export type ARTICLE_BY_SLUG_QUERY_RESULT = {
  _id: string
  title: string | null
  body: Array<{
    _key: string
    _type: string
    [key: string]: unknown
  }> | null
} | null

// Query TypeMap
import '@sanity/client'
declare module '@sanity/client' {
  interface SanityQueries {
    '*[_type == "article"] | order(title asc) { _id, title }': ARTICLES_QUERY_RESULT
    '*[_type == "blogPost"] | order(title asc) { _id, title }': BLOG_POSTS_QUERY_RESULT
    '*[_type == "blogPost" && slug.current == $slug][0]{ _id, title, body }': BLOG_POST_BY_SLUG_QUERY_RESULT
    '*[_type == "article" && slug.current == $slug][0]{ _id, title, body }': ARTICLE_BY_SLUG_QUERY_RESULT
  }
}
